"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import { ApiClientError } from "@/api/client";
import { decideG04, generateAnalysis, getAnalysis } from "@/api/analysis";
import type { AnalysisResponse, G04Decision } from "@/types/analysis";
import type { ArtifactRefDto } from "@/types/generated/api";
import styles from "./ControlTowerShell.module.css";

const decisions: Array<{ value: G04Decision; label: string }> = [{ value: "approve", label: "Approve G04" }, { value: "approve_with_comment", label: "Approve with comment" }, { value: "request_modification", label: "Request modification" }, { value: "reject", label: "Reject G04" }];
function correlationFrom(error: ApiClientError) { try { return (JSON.parse(error.responseBody ?? "{}") as { correlation_id?: string }).correlation_id ?? "unavailable"; } catch { return "unavailable"; } }
function operationKey(prefix: string, runId: string) { return `${prefix}-${runId}-${Date.now()}`; }

export function AnalysisReviewPanel({ runId, stateVersion, connectionStatus, artifacts, workflowEvents, refreshAuthoritativeState }: { runId: string; stateVersion: number; connectionStatus: string; artifacts: ArtifactRefDto[]; workflowEvents: Array<{ event_type: string; sequence: number; payload?: Record<string, unknown> }>; refreshAuthoritativeState?: () => Promise<unknown> }) {
  void artifacts; // Canonical evidence selection is backend-owned.
  const [analysis, setAnalysis] = useState<AnalysisResponse | null>(null); const [loading, setLoading] = useState(true); const [working, setWorking] = useState(false); const [empty, setEmpty] = useState(false); const [error, setError] = useState<string | null>(null); const [stale, setStale] = useState(false); const [decision, setDecision] = useState<G04Decision>("approve"); const [comment, setComment] = useState("");
  const latestEvent = useMemo(() => [...workflowEvents].reverse().find((event) => event.event_type.startsWith("ANALYSIS_AGENT_") || event.event_type.startsWith("G04_")), [workflowEvents]);
  const parityCompleted = workflowEvents.some((event) => event.event_type === "PARITY_BASELINE_COMPLETED");
  const analysisStarted = workflowEvents.some((event) => event.event_type === "ANALYSIS_AGENT_STARTED" || event.event_type === "ANALYSIS_REVIEWER_STARTED" || event.event_type === "G04_CREATED");
  const refresh = useCallback(async () => { if (!parityCompleted && !analysisStarted) { setLoading(false); setEmpty(true); return; } setLoading(true); setError(null); try { setAnalysis(await getAnalysis(runId)); setEmpty(false); } catch (reason: unknown) { if (reason instanceof ApiClientError && reason.status === 404) setEmpty(true); else setError(`Analysis could not be loaded. Correlation ID: ${reason instanceof ApiClientError ? correlationFrom(reason) : "unavailable"}`); } finally { setLoading(false); } }, [runId, parityCompleted, analysisStarted]);
  useEffect(() => { void refresh(); }, [refresh, stateVersion, latestEvent?.sequence]);

  async function generate() { setWorking(true); setError(null); setStale(false); try { const result = await generateAnalysis(runId, { expected_state_version: stateVersion, idempotency_key: operationKey("analysis", runId), correlation_id: operationKey("correlation", runId) }); setAnalysis(result); setEmpty(false); await refreshAuthoritativeState?.(); } catch (reason: unknown) { if (reason instanceof ApiClientError && reason.status === 409) { setStale(true); await refresh(); } else setError(`Analysis generation failed. Correlation ID: ${reason instanceof ApiClientError ? correlationFrom(reason) : "unavailable"}`); } finally { setWorking(false); } }
  async function submitDecision() { if (!analysis?.package || !analysis.package_checksum) return; if (decision === "approve_with_comment" && !comment.trim()) { setError("Add a comment before approving with comment."); return; } setWorking(true); setError(null); setStale(false); try { const result = await decideG04(runId, { expected_state_version: analysis.state_version, idempotency_key: operationKey("g04", runId), gate_version: analysis.gate_version, package_checksum: analysis.package_checksum, workspace_fingerprint: analysis.package.workspace_fingerprint, plan_version: analysis.package.plan_version, decision, comment: comment.trim() || null }); await refreshAuthoritativeState?.(); setAnalysis((current) => current ? { ...current, gate_status: result.status, gate_decision: result.decision, state_version: result.state_version, event_sequence: result.event_sequence } : current); await refresh(); } catch (reason: unknown) { if (reason instanceof ApiClientError && reason.status === 409) { setStale(true); await refresh(); } else setError(`G04 decision failed. Correlation ID: ${reason instanceof ApiClientError ? correlationFrom(reason) : "unavailable"}`); } finally { setWorking(false); } }

  const pkg = analysis?.package; const usage = pkg?.usage ?? {}; const approved = analysis?.gate_status === "approved" || analysis?.gate_status === "approved_with_comment"; const connectionLabel = connectionStatus === "reconnecting" ? "Connection lost. Reconnecting..." : connectionStatus === "recovering" ? "Refreshing authoritative analysis state..." : analysis?.status ?? "not loaded";
  return <section className={styles.panel} aria-labelledby="analysis-review-title"><div className={styles.previewHeader}><div><p className={styles.kicker}>S2-F04</p><h2 id="analysis-review-title">AI-assisted analysis and G04 review</h2><p className={styles.note}>Deterministic facts remain separate from the AI interpretation.</p></div><span className={styles.status}>{connectionLabel}</span></div>
    {loading ? <p role="status">Loading authoritative analysis...</p> : null}{error ? <p role="alert">{error}</p> : null}{stale ? <p role="alert">The analysis state is stale. The authoritative snapshot was reloaded; review the current package before retrying.</p> : null}
    {!loading && empty && !parityCompleted ? <p className={styles.note}>Waiting for parity baseline completion.</p> : null}
    {!loading && empty && parityCompleted ? <><p className={styles.note}>{analysisStarted ? "Analysis has been queued; waiting for the authoritative attempt." : "Analysis is queued automatically after parity completion."}</p>{!analysisStarted ? <button type="button" onClick={() => void generate()} disabled={working}>{working ? "Requesting retry..." : "Start analysis"}</button> : null}</> : null}
    {analysis?.status === "failed" || analysis?.status === "blocked" ? <div role="alert"><p>Analysis {analysis.failure_stage === "phase_reviewer" ? "reviewer" : analysis.failure_stage === "phase_proposer" ? "proposer" : ""} attempt failed: {analysis.error_code ?? "ANALYSIS_UNAVAILABLE"}. G04 is not presented as reviewed.</p><p>Cause: <code>{analysis.cause_code ?? "unavailable"}</code> · Subtype: <code>{analysis.failure_subtype ?? "unclassified"}</code> · Stage: <code>{analysis.failure_stage ?? "unknown"}</code> · Retryable: <code>{analysis.retryable ? "yes" : "no"}</code></p><p>Failed invocation: <code>{analysis.failed_invocation_id ?? "unavailable"}</code> · Correlation ID: <code>{analysis.correlation_id ?? "unavailable"}</code></p>{analysis.artifact_ids.map((id) => <a key={id} className={styles.actionLink} href={analysis.artifact_links[id] ?? `/api/v1/artifacts/${encodeURIComponent(id)}`} target="_blank" rel="noreferrer">Diagnostic evidence: {id}</a>)}{analysis.retryable ? <button type="button" onClick={() => void generate()} disabled={working}>{working ? "Retrying..." : "Retry analysis"}</button> : null}</div> : null}{analysis?.status === "in_progress" ? <p role="status">Analysis is running. This panel will refresh from the authoritative attempt.</p> : null}
    {pkg ? <><div className={styles.twoColumns}><div className={styles.previewPanel}><h3>Deterministic machine facts</h3><p className={styles.note}>Only registered artifact references are supplied to analysis.</p><ul className={styles.list}>{pkg.deterministic_input_artifacts.map((artifact) => <li key={artifact.artifact_id}><code>{artifact.artifact_id}</code><code>{artifact.checksum}</code></li>)}</ul><p className={styles.note}>Input checksum: <code>{pkg.narrative.deterministic_input_checksum}</code></p></div><div className={styles.previewPanel}><h3>AI interpretation</h3><p>{pkg.narrative.summary}</p><p><strong>Confidence:</strong> {pkg.narrative.evidence_confidence}</p><p><strong>Recommended next action:</strong> {pkg.narrative.recommended_next_action}</p>{pkg.narrative.risk_groups.length ? <><h4>Risk groups</h4><ul>{pkg.narrative.risk_groups.map((risk, index) => <li key={index}>{String(risk.name ?? JSON.stringify(risk))}</li>)}</ul></> : null}{pkg.narrative.unresolved_questions.length ? <><h4>Unresolved questions</h4><ul>{pkg.narrative.unresolved_questions.map((question) => <li key={question}>{question}</li>)}</ul></> : null}</div></div>
      <div className={styles.previewPanel}><h3>Phase Reviewer</h3><p><strong>Decision:</strong> {pkg.reviewer.decision}</p><p><strong>Confidence:</strong> {pkg.reviewer.confidence}</p><p>Proposer checksum: <code>{pkg.proposer_output_checksum}</code></p><p>Reviewer checksum: <code>{pkg.reviewer_output_checksum}</code></p>{pkg.reviewer.notes.length ? <ul>{pkg.reviewer.notes.map((note) => <li key={note}>{note}</li>)}</ul> : null}</div>
      <div className={styles.metadataGrid} aria-label="Analysis provenance"><div><dt>Proposer provider</dt><dd>{pkg.model_provenance.provider ?? "unknown"}</dd></div><div><dt>Proposer role</dt><dd>{pkg.model_provenance.role ?? "phase_proposer"}</dd></div><div><dt>Reviewer provider</dt><dd>{pkg.reviewer_provenance.provider ?? "unknown"}</dd></div><div><dt>Reviewer role</dt><dd>{pkg.reviewer_provenance.role ?? "phase_reviewer"}</dd></div><div><dt>Prompt</dt><dd>{pkg.prompt_version}</dd></div><div><dt>Schema</dt><dd>{pkg.schema_version}</dd></div><div><dt>Input tokens</dt><dd>{String(usage.input_tokens ?? 0)}</dd></div><div><dt>Output tokens</dt><dd>{String(usage.output_tokens ?? 0)}</dd></div><div><dt>Total cost</dt><dd>${Number(usage.total_cost_usd ?? 0).toFixed(6)}</dd></div></div>
      <div className={styles.previewPanel}><h3>Immutable analysis evidence</h3><p>G04 package checksum: <code>{analysis.package_checksum ?? "unavailable"}</code></p><ul className={styles.list}>{analysis.artifact_ids.map((id) => <li key={id}><a className={styles.actionLink} href={analysis.artifact_links[id] ?? `/api/v1/artifacts/${encodeURIComponent(id)}`} target="_blank" rel="noreferrer">{id}</a><code>{analysis.artifact_checksums[id]}</code></li>)}</ul></div>
      <div className={styles.previewPanel}><h3>G04: {analysis.gate_status}</h3>{approved ? <p role="status">G04 was accepted by the authoritative backend. The workflow status is not advanced by this button.</p> : <><label htmlFor="g04-decision">Decision</label><select id="g04-decision" value={decision} onChange={(event) => setDecision(event.target.value as G04Decision)}>{decisions.map((item) => <option key={item.value} value={item.value}>{item.label}</option>)}</select><label htmlFor="g04-comment">Review comment</label><textarea id="g04-comment" value={comment} onChange={(event) => setComment(event.target.value)} rows={3} placeholder="Optional rationale; required for approval with comment." /><button type="button" onClick={() => void submitDecision()} disabled={working || analysis.gate_status !== "pending"}>{working ? "Recording decision..." : "Record G04 decision"}</button></>}</div></> : null}
    {!loading && !analysis && !empty && !error ? <p className={styles.note}>Analysis has not been initialized.</p> : null}</section>;
}
