"use client";

import { type FormEvent, type RefObject, useEffect, useMemo, useRef, useState } from "react";
import { useRouter } from "next/navigation";
import { useAssistantConversation } from "@/hooks/useAssistantConversation";
import type { AssistantAnswerMode } from "@/types/assistant";
import { AssistantMessage as AssistantMessageBubble } from "./AssistantMessage";
import { AssistantEvidenceDrawer } from "./AssistantEvidenceDrawer";
import styles from "./ControlTowerShell.module.css";

const baseQuestions = ["Explain the current migration state and what is waiting now.","What has already been completed and what remains?","Why is the migration blocked, and what evidence proves it?","What is the next permitted action and why?","Summarize the most important risks, evidence, and operational usage."];
const phaseQuestions: Record<string, string[]> = { Analysis: ["Summarize the Analysis findings and their evidence.","Compare the proposer and reviewer conclusions."], Planning: ["Explain the current plan, highest risks, and validation commands."], Transformation: ["Explain what changed, why it changed, and what remains."], Validation: ["Explain every failed validation and the most likely root cause."] };

function storageKey(runId: string, name: string) { return `amfa:assistant:${runId}:${name}`; }
type PresentationState = "expanded" | "minimized" | "closed";
type AssistantStatus = { pending: boolean; error: boolean; model: string };
function readStorage(key: string) { try { return globalThis.localStorage?.getItem(key) ?? null; } catch { return null; } }
function writeStorage(key: string, value: string) { try { globalThis.localStorage?.setItem(key, value); } catch { /* optional */ } }
function readPresentation(runId: string): PresentationState { const stored = readStorage(storageKey(runId, "presentation")); if (stored === "expanded" || stored === "minimized" || stored === "closed") return stored; return readStorage(storageKey(runId, "open")) === "true" ? "expanded" : "closed"; }

function NextStepNavigation({ targetRoute, runId, label, reason, requiresApproval }: { targetRoute: string; runId: string; label: string; reason: string; requiresApproval: boolean }) {
  const router = useRouter();
  return <div className={styles.note}><button type="button" onClick={() => router.push(targetRoute.replace("{run_id}", encodeURIComponent(runId)))}>{label}</button><small> — {reason}{requiresApproval ? " · human approval required" : ""}</small></div>;
}
export function AssistantDock(props: { runId: string; phase?: string; stateVersion?: number; workflowStatus?: string }) {
  const [presentation, setPresentation] = useState<PresentationState>(() => readPresentation(props.runId));
  const [status, setStatus] = useState<AssistantStatus>({ pending: false, error: false, model: "Waiting for first answer" });
  const launcherRef = useRef<HTMLButtonElement>(null), restoreRef = useRef<HTMLButtonElement>(null), closeRef = useRef<HTMLButtonElement>(null);
  useEffect(() => { setPresentation(readPresentation(props.runId)); }, [props.runId]);
  function changePresentation(next: PresentationState) { setPresentation(next); writeStorage(storageKey(props.runId, "presentation"), next); }
  useEffect(() => { (presentation === "expanded" ? closeRef : presentation === "minimized" ? restoreRef : launcherRef).current?.focus(); }, [presentation]);
  return <div className={styles.assistantDock} data-assistant-presentation={presentation}>
    <div className={styles.assistantPopup + " " + styles.assistantExpanded} role="dialog" aria-modal="false" aria-label="Migration Follow-up Assistant" aria-hidden={presentation !== "expanded"} hidden={presentation !== "expanded"}><AssistantPanel {...props} onClose={() => changePresentation("closed")} onMinimize={() => changePresentation("minimized")} onStatus={setStatus} closeRef={closeRef} /></div>
    <div className={styles.assistantMinimized} aria-hidden={presentation !== "minimized"} hidden={presentation !== "minimized"}><span className={styles.assistantIcon} aria-hidden="true">✦</span><span className={styles.assistantMinimizedLabel}><strong>Migration Assistant</strong><small role={status.pending ? "status" : undefined} aria-live="polite">{status.pending ? "Thinking…" : status.error ? "Request failed" : status.model}</small></span>{status.pending ? <span className={styles.assistantPending} aria-hidden="true" /> : null}{status.error ? <span className={styles.assistantErrorMarker} aria-label="Request failed">!</span> : null}<button ref={restoreRef} className={styles.assistantDockButton} type="button" onClick={() => changePresentation("expanded")} aria-label="Expand Assistant">↗</button><button className={styles.assistantDockButton} type="button" onClick={() => changePresentation("closed")} aria-label="Close Assistant">×</button></div>
    <button ref={launcherRef} className={styles.assistantLauncher} type="button" onClick={() => changePresentation("expanded")} aria-expanded={presentation === "expanded"} aria-hidden={presentation !== "closed"} hidden={presentation !== "closed"} aria-label="Open Assistant"><span aria-hidden="true">✦</span><span>Ask Assistant</span></button>
  </div>;
}

export function AssistantPanel({ runId, phase = "unknown", stateVersion = 1, workflowStatus = "unknown", onClose, onMinimize, onStatus, closeRef }: { runId: string; phase?: string; stateVersion?: number; workflowStatus?: string; onClose?: () => void; onMinimize?: () => void; onStatus?: (status: AssistantStatus) => void; closeRef?: RefObject<HTMLButtonElement | null> }) {
  const [question, setQuestion] = useState(""), [answerMode, setAnswerMode] = useState<AssistantAnswerMode>("concise");
  const { messages, conversationId, state, error, submit } = useAssistantConversation(runId, stateVersion, phase, workflowStatus);
  const suggestions = useMemo(() => [...(phaseQuestions[phase] ?? []), ...baseQuestions].slice(0, 5), [phase]);
  const activeModel = [...messages].reverse().find((message) => message.role === "assistant")?.model ?? "Waiting for first answer";
  useEffect(() => { onStatus?.({ pending: state === "loading", error: Boolean(error), model: activeModel }); }, [activeModel, error, onStatus, state]);
  async function onSubmit(event?: FormEvent) { event?.preventDefault(); const value = question.trim(); if (!value || state === "loading") return; try { await submit(value, undefined, answerMode); setQuestion(""); } catch { /* owner renders durable failure */ } }
  return <section className={styles.assistantPanel} aria-labelledby="assistant-title">
    <div className={styles.assistantHeader}><div><p className={styles.kicker}>AMFA-221 · read-only</p><h2 id="assistant-title">Migration Follow-up Assistant</h2></div><div className={styles.assistantBadges}><span>State {stateVersion}</span><span>{workflowStatus}</span><span>{conversationId ?? "No conversation"}</span><div className={styles.assistantControls}>{onMinimize ? <button className={styles.assistantClose} type="button" onClick={onMinimize} aria-label="Minimize Assistant">—</button> : null}{onClose ? <button ref={closeRef} className={styles.assistantClose} type="button" onClick={onClose} aria-label="Close Assistant">×</button> : null}</div></div></div>
    <div className={styles.assistantInfo}><p className={styles.note}>Answers use the current backend projection, validated immutable evidence, and this run&apos;s persisted conversation. Mutations remain governed cockpit actions.</p>{state === "loading" && !messages.length ? <p role="status" aria-live="polite">Loading conversation…</p> : null}{state === "reconnecting" ? <p role="alert">Reconnecting to persisted conversation…</p> : null}{error ? <div className={styles.assistantError} role="alert"><strong>Assistant request failed</strong><span> {error.code ? `${error.code}: ` : ""}{error.message}{error.correlationId ? ` · ${error.correlationId}` : ""}</span></div> : null}{!messages.length && state !== "loading" ? <p className={styles.note}>Ask any read-only question about this migration.</p> : null}</div>
    <div className={styles.assistantConversationRegion} role="region" tabIndex={0} aria-label="Assistant conversation"><ol className={styles.assistantConversation}>{messages.map((message) => <li key={message.message_id} className={styles.assistantConversationItem}><AssistantMessageBubble message={message} /><div className={styles.assistantMessageMeta}><span>Blocker: {message.current_blocker}</span><span>Next: {message.next_permitted_action}</span></div>{message.stale ? <p role="status">This answer is stale relative to the current workflow state.</p> : null}{message.failure_reason ? <p role="alert">Failure: {message.error_code ? `${message.error_code} · ` : ""}{message.failure_reason}{message.correlation_id ? ` · ${message.correlation_id}` : ""}</p> : null}{message.role === "assistant" && message.response_status === "failed" ? (() => { const original = [...messages].reverse().find((candidate) => candidate.role === "user" && candidate.conversation_id === message.conversation_id && candidate.message_order < message.message_order); return <button type="button" aria-label="Retry assistant response" disabled={state === "loading" || !original} onClick={() => { if (original) void submit(original.answer, message.message_id, message.answer_mode || answerMode).catch(() => undefined); }}>Retry</button>; })() : null}{message.summary ? <p>{message.summary}</p> : null}{message.intent ? <small>Intent: {message.intent} · Capability: {message.capability_key || "unavailable"} · Mode: {message.answer_mode || "concise"}</small> : null}{message.missing_information?.length ? <small>Missing information: {message.missing_information.join(", ")}</small> : null}{message.suggested_follow_ups?.length ? <small>Suggested follow-ups: {message.suggested_follow_ups.join(" · ")}</small> : null}{message.role === "assistant" ? <AssistantEvidenceDrawer citations={message.citations ?? []} /> : null}{(message.next_step_proposals ?? []).map((proposal) => proposal.target_route ? <NextStepNavigation key={proposal.action_key} targetRoute={proposal.target_route} runId={runId} label={proposal.label} reason={proposal.reason} requiresApproval={proposal.requires_human_approval} /> : <div key={proposal.action_key} className={styles.note}><span>{proposal.label}</span><small> — {proposal.reason}{proposal.requires_human_approval ? " · human approval required" : ""}</small></div>)}<small>{message.response_status}</small>{message.operational_statistics?.total_tokens == null ? <small>Operational statistics unavailable</small> : <small> · {message.operational_statistics.total_tokens} tokens · {message.operational_statistics.total_cost_usd == null ? "cost unavailable" : `$${message.operational_statistics.total_cost_usd.toFixed(6)}`}</small>}</li>)}</ol><div aria-label="Suggested assistant questions" className={styles.assistantSuggestions}>{suggestions.map((suggestion) => <button type="button" key={suggestion} onClick={() => setQuestion(suggestion)}>{suggestion}</button>)}</div></div>
    <form className={styles.assistantComposer} onSubmit={onSubmit}><label htmlFor="assistant-question">Ask about this migration</label><textarea id="assistant-question" rows={3} value={question} onChange={(event) => setQuestion(event.target.value)} onKeyDown={(event) => { if (event.key === "Enter" && !event.shiftKey) { event.preventDefault(); void onSubmit(); } }} disabled={state === "loading"} /><div><label htmlFor="assistant-answer-mode">Answer depth</label><select id="assistant-answer-mode" aria-label="Answer mode" value={answerMode} onChange={(event) => setAnswerMode(event.target.value as AssistantAnswerMode)}><option value="concise">Concise</option><option value="detailed">Detailed</option><option value="deep">Deep</option></select><button type="submit" disabled={!question.trim() || state === "loading"}>{state === "loading" ? "Answering…" : "Send"}</button></div></form>
  </section>;
}
