"use client";
import { useEffect, useState } from "react";
import { ApiClientError } from "@/api/client";
import { decideG03, getBaselineSummary, qualifyBaseline } from "@/api/baselineG03";
import type { BaselineAssessmentResponse } from "@/types/generated/api";
export function BaselineQualificationPanel({runId,stateVersion,workflowEvents=[],refreshAuthoritativeState}:{runId:string;stateVersion:number;workflowEvents?:Array<{event_type:string}>;refreshAuthoritativeState?:()=>Promise<void>}) {
 const [assessment,setAssessment]=useState<BaselineAssessmentResponse|null>(null); const [busy,setBusy]=useState(false); const [error,setError]=useState<string|null>(null);
 const qualificationRecorded=workflowEvents.some((event)=>["BASELINE_BLOCKED","BASELINE_QUALIFIED","G03_CREATED","G03_APPROVED","G03_REJECTED"].includes(event.event_type));
 useEffect(()=>{if(!qualificationRecorded)return; void getBaselineSummary(runId).then(setAssessment).catch((reason: unknown)=>{if(!(reason instanceof ApiClientError && reason.status===404))setError("Baseline qualification state could not be loaded.")})},[runId,stateVersion,workflowEvents.length,qualificationRecorded]);
 const canQualify=workflowEvents.some((event)=>event.event_type==="G02_APPROVED") && workflowEvents.some((event)=>event.event_type==="BASELINE_INSTALL_SUCCEEDED");
 const act=async (fn:()=>Promise<BaselineAssessmentResponse>)=>{setBusy(true);setError(null);try{setAssessment(await fn()); await refreshAuthoritativeState?.()}catch(e){setError(e instanceof Error?e.message:"Request failed")}finally{setBusy(false)}};
 return <section aria-label="Baseline qualification"><h2>Baseline qualification / G03</h2>{assessment?<><p data-testid="qualification-status">{assessment.status}</p><p>Policy: {assessment.policy}</p><p>Evidence: {assessment.evidence_set_checksum}</p>{assessment.blockers.length>0?<ul>{assessment.blockers.map(x=><li key={x}>{x}</li>)}</ul>:<p>Evidence is ready for review.</p>}{assessment.g03_decision?<p role="status">G03 decision: {assessment.g03_decision}</p>:<button disabled={busy||assessment.blockers.length>0} onClick={()=>void act(()=>decideG03(runId,{expected_state_version:assessment.state_version,idempotency_key:`g03-${Date.now()}`,actor:"reviewer",decision:"approved"}))}>Approve G03</button>}</>:canQualify?<><button disabled={busy} onClick={()=>void act(()=>qualifyBaseline(runId,{expected_state_version:stateVersion,idempotency_key:`qualify-${Date.now()}`,actor:"reviewer",policy:"strict_clean"}))}>Qualify baseline</button></>:<p>G03 remains hidden until G02 approval and baseline evidence are complete.</p>}{error?<p role="alert">{error}</p>:null}</section>
}
