"use client";
import { useEffect, useState } from "react";
import { ApiClientError } from "@/api/client";
import { decideG03, getBaselineSummary, qualifyBaseline } from "@/api/baselineG03";
import type { BaselineAssessmentResponse } from "@/types/generated/api";
import { headingTag, type PanelHeadingLevel } from "./control-tower/semanticHeading";
import type { AuthoritativePackageLoad } from "./control-tower/authoritativePackageLoad";
export function BaselineQualificationPanel({runId,stateVersion,workflowEvents=[],refreshAuthoritativeState,authoritativeAssessment,headingLevel=2}:{runId:string;stateVersion:number;workflowEvents?:Array<{event_type:string}>;refreshAuthoritativeState?:()=>Promise<void>;authoritativeAssessment?:AuthoritativePackageLoad<BaselineAssessmentResponse>;headingLevel?:PanelHeadingLevel}) {
 const Heading=headingTag(headingLevel);
 const externallyLoaded=authoritativeAssessment!==undefined;
 const [localAssessment,setAssessment]=useState<BaselineAssessmentResponse|null>(null); const [busy,setBusy]=useState(false); const [error,setError]=useState<string|null>(null);
 const qualificationRecorded=workflowEvents.some((event)=>["BASELINE_BLOCKED","BASELINE_QUALIFIED","G03_CREATED","G03_APPROVED","G03_REJECTED"].includes(event.event_type));
 useEffect(()=>{if(externallyLoaded||!qualificationRecorded)return; void getBaselineSummary(runId).then(setAssessment).catch((reason: unknown)=>{if(!(reason instanceof ApiClientError && reason.status===404))setError("Baseline qualification state could not be loaded.")})},[externallyLoaded,runId,stateVersion,workflowEvents.length,qualificationRecorded]);
 const assessment=externallyLoaded?(authoritativeAssessment.status==="ready"?authoritativeAssessment.value:null):localAssessment;
 const externalPending=externallyLoaded&&authoritativeAssessment.status!=="ready";
 const canQualify=workflowEvents.some((event)=>event.event_type==="G02_APPROVED") && workflowEvents.some((event)=>event.event_type==="BASELINE_INSTALL_SUCCEEDED");
 const act=async (fn:()=>Promise<BaselineAssessmentResponse>)=>{setBusy(true);setError(null);try{setAssessment(await fn()); await refreshAuthoritativeState?.()}catch(e){setError(e instanceof Error?e.message:"Request failed")}finally{setBusy(false)}};
 return <section aria-label="Baseline qualification"><Heading>Baseline qualification</Heading>{externallyLoaded&&authoritativeAssessment.status==="loading"?<p>Loading baseline qualification package</p>:null}{externallyLoaded&&authoritativeAssessment.status==="unavailable"?<div><p role="status">Baseline qualification package is unavailable because the response was invalid.</p><button type="button" onClick={authoritativeAssessment.retry}>Retry baseline qualification</button></div>:null}{externallyLoaded&&authoritativeAssessment.status==="error"?<div><p role="alert">Baseline qualification package could not be loaded.</p><button type="button" onClick={authoritativeAssessment.retry}>Retry baseline qualification</button></div>:null}{!externalPending&&assessment?<><p data-testid="qualification-status">{assessment.status}</p><p>Policy: {assessment.policy}</p><p>Evidence: {assessment.evidence_set_checksum}</p>{assessment.blockers.length>0?<ul>{assessment.blockers.map(x=><li key={x}>{x}</li>)}</ul>:<p>Evidence is ready for review.</p>}{assessment.g03_decision?<p role="status">Baseline decision: {assessment.g03_decision}</p>:<button disabled={busy||assessment.blockers.length>0} onClick={()=>void act(()=>decideG03(runId,{expected_state_version:assessment.state_version,idempotency_key:`g03-${Date.now()}`,actor:"reviewer",decision:"approved"}))}>Approve baseline qualification</button>}</>:!externalPending&&canQualify?<><button disabled={busy} onClick={()=>void act(()=>qualifyBaseline(runId,{expected_state_version:stateVersion,idempotency_key:`qualify-${Date.now()}`,actor:"reviewer",policy:"strict_clean"}))}>Qualify baseline</button></>:!externalPending?<p>Baseline qualification remains hidden until source snapshot approval and baseline evidence are complete.</p>:null}{error?<p role="alert">{error}</p>:null}</section>
}
