"use client";
import { useCallback, useEffect, useState } from "react";
import { ApiClientError } from "@/api/client";
import { captureDiscovery, getDiscovery } from "@/api/discovery";
import type { DiscoveryEvidence } from "@/types/discovery";
import styles from "./ControlTowerShell.module.css";
import localStyles from "./DiscoveryFindingsPanel.module.css";

type Artifact = { artifact_id: string; checksum: string };
export function DiscoveryFindingsPanel({ runId, stateVersion, connectionStatus, artifacts = [] }: { runId: string; stateVersion: number; connectionStatus: string; artifacts?: Artifact[] }) {
 const [evidence,setEvidence]=useState<DiscoveryEvidence>(); const [filter,setFilter]=useState(""); const [error,setError]=useState(""); const [empty,setEmpty]=useState(false); const [working,setWorking]=useState(false); const [stale,setStale]=useState(false);
 const correlationId=(reason: ApiClientError)=>{try{return JSON.parse(reason.responseBody||"{}").correlation_id||"unavailable"}catch{return "unavailable"}};
 const refresh=useCallback(()=>getDiscovery(runId).then(value=>{setEvidence(value);setEmpty(false);setError("")}).catch(reason=>{if(reason instanceof ApiClientError&&reason.status===404)setEmpty(true);else setError(`Analysis findings could not be loaded. Correlation ID: ${reason instanceof ApiClientError?correlationId(reason):"unavailable"}`)}),[runId]);
 useEffect(()=>{setEvidence(undefined);setError("");setEmpty(false);void refresh()},[runId,stateVersion,refresh]);
 async function capture(){setWorking(true);setError("");setStale(false);try{const ids=artifacts.map(x=>x.artifact_id);await captureDiscovery(runId,{expected_state_version:stateVersion,idempotency_key:`discovery-${runId}-${Date.now()}`,actor:"control-tower",prerequisite_artifact_ids:ids,prerequisite_artifact_checksums:Object.fromEntries(artifacts.map(x=>[x.artifact_id,x.checksum]))});await refresh()}catch(reason){if(reason instanceof ApiClientError&&reason.status===409){setStale(true);await refresh()}else if(reason instanceof ApiClientError&&[401,403].includes(reason.status))setError(`You are not authorized to run the analysis scan. Correlation ID: ${correlationId(reason)}`);else if(reason instanceof ApiClientError)setError(`The analysis scan could not be captured. Correlation ID: ${correlationId(reason)}`);else setError("The analysis scan could not be captured.")}finally{setWorking(false)}}
 if(error)return <section className={styles.panel}><p role="alert">{error}</p></section>; if(empty)return <section className={styles.panel}><h2>Application analysis findings</h2><button onClick={()=>void capture()} disabled={working||!artifacts.length}>{working?"Scanning...":"Run analysis scan"}</button><p>No authoritative analysis findings are available yet.</p></section>; if(!evidence)return <section className={styles.panel}><h2>Application analysis findings</h2><p role="status">Loading authoritative analysis findings...</p></section>;
 const scanners=evidence.scanner_results.filter(x=>x.scanner.includes(filter));
 const summaryValue=(value: unknown)=>typeof value==="string"?value.replace(/[_-]+/g," "):JSON.stringify(value);
 return <section className={styles.panel} aria-labelledby="analysis-findings-title"><h2 id="analysis-findings-title">Application analysis findings</h2><p>{connectionStatus==="reconnecting"?"Connection lost. Reconnecting...":connectionStatus==="recovering"?"Refreshing authoritative analysis state...":`Authoritative state: ${evidence.status}`}</p><button onClick={()=>void capture()} disabled={working||!artifacts.length}>{working?"Scanning...":"Run analysis scan"}</button>{evidence.status==="blocked"?<p role="alert">The analysis scan is blocked: {evidence.error_code||"DISCOVERY_SCANNER_BLOCKED"}. Safe partial findings remain available.</p>:null}{stale?<p role="alert">The run changed. Authoritative state was reloaded before retrying.</p>:null}<label>Filter scanners <input value={filter} onChange={x=>setFilter(x.target.value)} /></label>{!scanners.length?<p>No scanner results match this filter.</p>:<ul className={localStyles.scannerList}>{scanners.map(s=><li key={s.scanner}><strong>{s.scanner}: {s.status}</strong>{s.findings.length?<p>{s.findings.length} finding{s.findings.length===1?"":"s"} recorded.</p>:null}{s.findings.length?<ul className={localStyles.findingSummary}>{s.findings.map(f=><li key={f.key}><code>{f.key}</code><span>{summaryValue(f.value)}</span></li>)}</ul>:null}<details className={localStyles.rawFindings}><summary>Show raw findings</summary>{s.findings.map(f=><div key={f.key}><code>{f.key}</code> <code>{JSON.stringify(f.value)}</code><small>{f.confidence} confidence — {f.source_references.join(", ")||"no source reference"}</small></div>)}</details>{s.unknowns.map(x=><p key={x}>Unknown: {x}</p>)}</li>)}</ul>}<details className={localStyles.rawFindings}><summary>Raw evidence identifiers</summary>{evidence.artifact_ids.map(id=><div key={id}><a href={`/api/v1/artifacts/${encodeURIComponent(id)}`}>Open artifact {id}</a> <code>{evidence.artifact_checksums[id] ?? ""}</code></div>)}</details></section>;
}
