"use client";
import { useCallback, useEffect, useState } from "react";
import { ApiClientError } from "@/api/client";
import { captureDiscovery, getDiscovery } from "@/api/discovery";
import type { DiscoveryEvidence } from "@/types/discovery";
import styles from "./ControlTowerShell.module.css";

type Artifact = { artifact_id: string; checksum: string };
export function DiscoveryFindingsPanel({ runId, stateVersion, connectionStatus, artifacts = [] }: { runId: string; stateVersion: number; connectionStatus: string; artifacts?: Artifact[] }) {
 const [evidence,setEvidence]=useState<DiscoveryEvidence>(); const [filter,setFilter]=useState(""); const [error,setError]=useState(""); const [empty,setEmpty]=useState(false); const [working,setWorking]=useState(false); const [stale,setStale]=useState(false);
 const correlationId=(reason: ApiClientError)=>{try{return JSON.parse(reason.responseBody||"{}").correlation_id||"unavailable"}catch{return "unavailable"}};
 const refresh=useCallback(()=>getDiscovery(runId).then(value=>{setEvidence(value);setEmpty(false);setError("")}).catch(reason=>{if(reason instanceof ApiClientError&&reason.status===404)setEmpty(true);else setError(`Discovery findings could not be loaded. Correlation ID: ${reason instanceof ApiClientError?correlationId(reason):"unavailable"}`)}),[runId]);
 useEffect(()=>{setEvidence(undefined);setError("");setEmpty(false);void refresh()},[runId,stateVersion,refresh]);
 async function capture(){setWorking(true);setError("");setStale(false);try{const ids=artifacts.map(x=>x.artifact_id);await captureDiscovery(runId,{expected_state_version:stateVersion,idempotency_key:`discovery-${runId}-${Date.now()}`,actor:"control-tower",prerequisite_artifact_ids:ids,prerequisite_artifact_checksums:Object.fromEntries(artifacts.map(x=>[x.artifact_id,x.checksum]))});await refresh()}catch(reason){if(reason instanceof ApiClientError&&reason.status===409){setStale(true);await refresh()}else if(reason instanceof ApiClientError&&[401,403].includes(reason.status))setError(`You are not authorized to run discovery. Correlation ID: ${correlationId(reason)}`);else if(reason instanceof ApiClientError)setError(`Discovery could not be captured. Correlation ID: ${correlationId(reason)}`);else setError("Discovery could not be captured.")}finally{setWorking(false)}}
 if(error)return <section className={styles.panel}><p role="alert">{error}</p></section>; if(empty)return <section className={styles.panel}><h2>Deterministic discovery findings</h2><button onClick={()=>void capture()} disabled={working||!artifacts.length}>{working?"Discovering...":"Run discovery"}</button><p>No authoritative discovery findings are available yet.</p></section>; if(!evidence)return <section className={styles.panel}><h2>Deterministic discovery findings</h2><p role="status">Loading authoritative discovery findings...</p></section>;
 const scanners=evidence.scanner_results.filter(x=>x.scanner.includes(filter)); return <section className={styles.panel} aria-labelledby="discovery-title"><h2 id="discovery-title">Deterministic discovery findings</h2><p>{connectionStatus==="reconnecting"?"Connection lost. Reconnecting...":connectionStatus==="recovering"?"Refreshing authoritative discovery state...":`Authoritative state: ${evidence.status}`}</p><button onClick={()=>void capture()} disabled={working||!artifacts.length}>{working?"Discovering...":"Run discovery"}</button>{evidence.status==="blocked"?<p role="alert">Discovery is blocked: {evidence.error_code||"DISCOVERY_SCANNER_BLOCKED"}. Safe partial findings remain available.</p>:null}{stale?<p role="alert">The run changed. Authoritative state was reloaded before retrying.</p>:null}<label>Filter scanners <input value={filter} onChange={x=>setFilter(x.target.value)} /></label>{!scanners.length?<p>No discovery findings match this filter.</p>:<ul className={styles.list}>{scanners.map(s=><li key={s.scanner}><strong>{s.scanner}: {s.status}</strong>{s.findings.map(f=><div key={f.key}><code>{f.key}</code> <span>{JSON.stringify(f.value)}</span><small>{f.confidence} confidence — {f.source_references.join(", ")||"no source reference"}</small></div>)}{s.unknowns.map(x=><p key={x}>Unknown: {x}</p>)}</li>)}</ul>}<p>{evidence.artifact_ids.map(id=><a key={id} href={`/api/v1/artifacts/${encodeURIComponent(id)}`}>Open artifact {id}</a>)}</p></section>;
}
