"use client";
import { useCallback, useEffect, useState } from "react";
import { ApiClientError } from "@/api/client";
import { getExecutionProfiles, resolveExecutionProfiles, selectExecutionProfile } from "@/api/executionProfiles";
import type { AuthoritativeRunStateDto, ExecutionProfileResponse, RuntimeCandidate } from "@/types/generated/api";
import styles from "./ControlTowerShell.module.css";

function displayExecutable(path: string) { const parts = path.replaceAll("\\", "/").split("/"); return `.../${parts.slice(-2).join("/")}`; }
export function ExecutionProfilePanel({ runId, initialState, candidates = [], sourceTypescriptExact, sourceRxjsExact }: { runId: string; initialState: AuthoritativeRunStateDto; candidates?: RuntimeCandidate[]; sourceTypescriptExact?: string | null; sourceRxjsExact?: string | null }) {
  const [resolution, setResolution] = useState<ExecutionProfileResponse | null>(null);
  const [loading, setLoading] = useState(true); const [submitting, setSubmitting] = useState(false); const [error, setError] = useState<string | null>(null); const [missing, setMissing] = useState(false);
  const sourceAngularExact = initialState.source_angular_exact ?? null;
  const refresh = useCallback(() => { setLoading(true); setError(null); getExecutionProfiles(runId).then((value) => { setResolution(value); setMissing(false); }).catch((reason: unknown) => { if (reason instanceof ApiClientError && reason.status === 404) setMissing(true); else setError("Execution profile resolution could not be loaded."); }).finally(() => setLoading(false)); }, [runId]);
  useEffect(() => { refresh(); }, [refresh]);
  async function resolve() { if (!sourceAngularExact) { setError("The exact Angular source version is unresolved in authoritative run state."); return; } setSubmitting(true); setError(null); try { setResolution(await resolveExecutionProfiles(runId, { expected_state_version: initialState.state_version, idempotency_key: `execution-profile-${runId}-${Date.now()}`, actor: "control-tower", source_angular_exact: sourceAngularExact, source_typescript_exact: sourceTypescriptExact, source_rxjs_exact: sourceRxjsExact, candidates, validated_at: new Date().toISOString() })); setMissing(false); } catch (reason: unknown) { setError(reason instanceof ApiClientError && reason.status === 409 ? "The run state or G02 boundary is stale. Refresh the authoritative run state before resolving again." : "Execution profile resolution failed."); } finally { setSubmitting(false); } }
  async function select(profileId: string, checksum: string) { setSubmitting(true); setError(null); try { setResolution(await selectExecutionProfile(runId, profileId, { expected_state_version: resolution?.state_version ?? initialState.state_version, idempotency_key: `execution-profile-select-${runId}-${checksum}`, actor: "control-tower", profile_id: profileId, checksum })); } catch (reason: unknown) { setError(reason instanceof ApiClientError && reason.status === 409 ? "The execution profile is stale. Refresh the authoritative run state and resolve again." : "The execution profile selection could not be recorded."); } finally { setSubmitting(false); } }
  const selected = resolution?.selected_profile;
  return <section className={styles.panel} aria-label="Source-compatible execution profile">
    <div className={styles.previewHeader}><div><p className={styles.kicker}>S1-F09</p><h2>Source-compatible ExecutionProfile</h2></div>{resolution ? <strong>{resolution.status}</strong> : null}</div>
    {loading ? <p className={styles.note}>Loading runtime profile evidence...</p> : null}
    {error ? <p role="alert">{error}</p> : null}
    {!loading && missing ? <div><p className={styles.note}>No runtime resolution exists for this run. Resolve the exact source-compatible Node/npm/npx profile.</p>{sourceAngularExact ? <button type="button" onClick={resolve} disabled={submitting}>{submitting ? "Resolving..." : "Resolve runtime profiles"}</button> : <p role="alert">The exact Angular source version is not available from authoritative evidence yet.</p>}{candidates.length === 0 ? <p className={styles.note}>The backend will use the latest persisted environment inventory.</p> : null}</div> : null}
    {resolution?.status === "blocked" ? <div role="alert"><p>Baseline is blocked. No compatible approved runtime is available.</p><ul className={styles.list}>{resolution.blockers.map((blocker) => <li key={blocker}><code>{blocker}</code></li>)}</ul>{resolution.guidance.map((item) => <p className={styles.note} key={item}>{item}</p>)}</div> : null}
    {resolution && resolution.status !== "blocked" ? <><div className={styles.dimensionGrid} aria-label="Execution profile summary"><div><span>Angular source</span><strong>{resolution.source_angular_exact}</strong></div><div><span>Policy</span><strong>{resolution.policy_version}</strong></div><div><span>State version</span><strong>{resolution.state_version}</strong></div><div><span>Checksum</span><strong>{selected?.checksum ?? "Selection required"}</strong></div></div><h3>Compatible runtime candidates</h3><ul className={styles.list}>{resolution.compatible_profiles.map((profile) => <li key={profile.profile_id}><span><strong>{profile.profile_id}</strong><br /><code>{displayExecutable(profile.node_executable)}</code> · Node {profile.node_exact} · npm {profile.package_manager_exact} · npx {profile.npx_exact}</span>{selected?.profile_id === profile.profile_id ? <strong>Selected</strong> : <button type="button" onClick={() => select(profile.profile_id, profile.checksum)} disabled={submitting || resolution.status !== "selection_required"}>{submitting ? "Selecting..." : "Select"}</button>}</li>)}</ul>{selected ? <p className={styles.note}>This exact checksum-bound profile will be used for baseline commands.</p> : <p className={styles.note}>Select one approved candidate before baseline commands can start.</p>}</> : null}
  </section>;
}
