"use client";
import { useCallback, useEffect, useState } from "react";
import { ApiClientError } from "@/api/client";
import { captureParityBaseline, getParityBaseline } from "@/api/parityBaseline";
import type { ParityBaselineResponse } from "@/types/parityBaseline";
import styles from "./ControlTowerShell.module.css";
export function ParityBaselinePanel({ runId, stateVersion, connectionStatus, artifacts=[] }: { runId: string; stateVersion: number; connectionStatus: string; artifacts?: Array<{artifact_id:string;checksum:string}> }) {
 const [value,setValue]=useState<ParityBaselineResponse>(); const [loading,setLoading]=useState(true); const [working,setWorking]=useState(false); const [error,setError]=useState(""); const [stale,setStale]=useState(false);
 const refresh=useCallback(async()=>{try{setLoading(true);setValue(await getParityBaseline(runId));setError("")}catch(reason){if(reason instanceof ApiClientError&&reason.status===404)setValue(undefined);else setError("Parity evidence could not be loaded.")}finally{setLoading(false)}},[runId]);
 useEffect(()=>{void refresh()},[refresh,stateVersion]);
 async function capture(){setWorking(true);setStale(false);try{await captureParityBaseline(runId,{expected_state_version:stateVersion,idempotency_key:`parity-baseline-${runId}-${Date.now()}`,prerequisite_artifact_ids:artifacts.map(x=>x.artifact_id),prerequisite_artifact_checksums:Object.fromEntries(artifacts.map(x=>[x.artifact_id,x.checksum]))});await refresh()}catch(reason){if(reason instanceof ApiClientError&&reason.status===409){setStale(true);await refresh()}else setError("Parity evidence could not be captured.")}finally{setWorking(false)}}
 const payload=value?.payload; return <section className={styles.panel} aria-labelledby="parity-baseline-title"><div className={styles.header}><div><p className={styles.kicker}>Application comparison</p><h2 id="parity-baseline-title">Application comparison</h2><p className={styles.note}>Structural evidence only; functional parity remains manual validation.</p></div><span className={styles.status}>{value?.status??"not captured"}</span></div><p className={styles.note} role="status">{connectionStatus==="open"?"Live authoritative parity state":`Connection: ${connectionStatus}`}</p>{loading?<p role="status">Loading parity evidence...</p>:null}{error?<p role="alert">{error}</p>:null}{stale?<p role="alert">The run changed. Refresh the authoritative state before retrying.</p>:null}{!loading&&!value?<div className={styles.previewPanel}><p>No parity evidence has been captured.</p><button onClick={()=>void capture()} disabled={working||connectionStatus!=="open"||!artifacts.length}>{working?"Inspecting...":"Inspect parity evidence"}</button></div>:null}{value?<div className={styles.previewPanel}>{value.status==="blocked"?<p role="alert">Inspection blocked: {value.error_code}</p>:null}<h3>Routes</h3><pre className={styles.logViewer}>{JSON.stringify(payload?.routes??[],null,2)}</pre><h3>API and auth</h3><pre className={styles.logViewer}>{JSON.stringify(payload?.backend_integration??{},null,2)}</pre><h3>Behavior-sensitive files</h3><ul className={styles.list}>{(payload?.sensitive_files??[]).map(item=><li key={item.file}><code>{item.file}</code><span>{item.indicators.join(", ")||item.classification}</span></li>)}</ul>{(payload?.unknowns??[]).map(item=><p key={item}>Manual review: {item}</p>)}<p>{value.artifact_ids.map(id=><a key={id} href={`/api/v1/artifacts/${encodeURIComponent(id)}`}>Open artifact {id}</a>)}</p></div>:null}</section>;
}