export type TransformationProjection = {
  run_id: string;
  continuation_id: string;
  stage_id: string;
  status: string;
  current_node: string;
  state_version: number;
  stage_status: string;
  source_version: string | null;
  target_version: string | null;
  checkpoint_kind: string | null;
  workspace_fingerprint: string | null;
  active_gate: string | null;
  active_gate_package_checksum: string | null;
  active_command_id: string | null;
  active_command_status: string | null;
  active_prompt_id: string | null;
  active_prompt_checksum: string | null;
  active_prompt_text: string | null;
  active_prompt_options: Array<{ option_id: string; label: string }>;
  active_prompt_explanation: {
    summary: string;
    option_effects: string[];
    risk_note: string;
    source: string;
  } | null;
  repair_attempt_id: string | null;
  repair_status: string | null;
  repair_risk_level: string | null;
  repair_proposal_checksum: string | null;
  repair_review_checksum: string | null;
  repair_apply_checksum: string | null;
  repair_validation_checksum: string | null;
  route_stages: Array<{
    stage_id: string;
    source_version: string | null;
    target_version: string | null;
    status: string;
  }>;
  sealed_chain_hash: string | null;
  last_error_code: string | null;
  cancel_requested_at: string | null;
};
