"""Non-secret application metadata. Configuration arrives in AMF-S0-03."""
APP_NAME = "AI Frontend Migration Factory API"
APP_VERSION = "0.1.0"
APP_ENVIRONMENT = "development"
APP_DESCRIPTION = "Backend execution-authority API for controlled frontend migration workflows."
